# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-14 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_auto_20161214_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='XX', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
