# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-15 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='simulator.Country'),
        ),
    ]
