# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-15 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_auto_20161214_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='city_name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
