# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-17 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0008_auto_20161215_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='importance',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='airport',
            name='importance',
            field=models.IntegerField(default=1),
        ),
    ]
