# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-17 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0009_auto_20161216_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='airline_count',
            field=models.IntegerField(default=0),
        ),
    ]
